name: Build and execute Bitextor tests
on: [push, pull_request]
jobs:
   build_and_testing:
      name: Build and testing
      runs-on: ubuntu-20.04
      timeout-minutes: 1440
      steps:
      -  name: Set distrib release version if not set
         env:
            DR_VERSION: 20.04
         run: |
            # Hack to get setup-python to work on act (https://github.com/nektos/act/issues/213)
            if [ ! -f "/etc/lsb-release" ] ; then
               echo "DISTRIB_RELEASE=$DR_VERSION" > /etc/lsb-release
            fi
      -  name: Install required linux packages
         run: |
            apt-get --assume-yes update || sudo apt-get --assume-yes update || true
            # Docker default user is root, but is not on Github Action (https://docs.github.com/en/free-pro-team@latest/actions/reference/specifications-for-github-hosted-runners#administrative-privileges-of-github-hosted-runners),
            #  so we use sudo and Docker will not complain and Github Actions will work
            apt-get --assume-yes install sudo || true
            sudo apt-get --assume-yes install cmake automake liblzma-dev time poppler-utils httrack libboost-all-dev pkg-config curl git pigz wget zlib1g zlib1g-dev libgoogle-perftools-dev libsparsehash-dev coreutils uchardet libuchardet-dev libzip-dev
            sudo apt-get --assume-yes --reinstall install build-essential g++
      -  name: Set up Python3
         uses: actions/setup-python@v2
         with:
            python-version: '3.8.5'
            architecture: 'x64'
      -  name: Install Python dev tools
         run: |
            pip3 install --upgrade pip
            sudo apt-get --assume-yes install python3-venv python3-setuptools
            pip3 install Cython
      -  name: Set up JDK
         uses: actions/setup-java@v1
         with:
            java-version: 8
            java-package: jdk
            architecture: x64
#      -  name: Download protobuf
#         run: |
#            wget https://github.com/protocolbuffers/protobuf/releases/download/v3.11.4/protobuf-all-3.11.4.tar.gz
#            tar -zxvf protobuf-all-3.11.4.tar.gz
#      -  name: Install protobuf
#         working-directory: ./protobuf-3.11.4
#         run: |
#            ./configure
#            make
#            make check
#            sudo make install
#            sudo ldconfig
#            pip3 install pycld3
      -  uses: actions/checkout@v2
      -  name: Checkout submodules
         run: git submodule update --init --force --recursive
      -  name: Install additional python requirements
         run: |
            pip3 install -r requirements.txt
            pip3 install -r bicleaner/requirements.txt
            pip3 install https://github.com/kpu/kenlm/archive/master.zip --install-option="--max_order 7"
            pip3 install -r bifixer/requirements.txt
      -  name: Compile Biroamer
         run: |
            cd biroamer/fast_align
            mkdir build
            cd build
            cmake ..
            make
            cd ../../..
            pip3 install -r biroamer/requirements.txt
            python -m spacy download en_core_web_sm
      -  name: Setup golang
         uses: actions/setup-go@v2
         with:
            go-version: 1.14.6
      -  name: Install giawarc and giashard
         run: |
            go get github.com/paracrawl/giawarc/...
            go get github.com/paracrawl/giashard/...
      -  name: Compiling bitextor and submodules
         run: |
            ./autogen.sh
            make
      -  name: Run tests
         env:
            BITEXTOR: ${{ github.workspace }}
         run: |
            chmod 775 ./run-tests-min.sh
            ./run-tests-min.sh -w "$BITEXTOR" -j 4
      -  name: Print log of tests which failed
         if: ${{ always() }}
         env:
            WORK: ${{ github.workspace }}
         run: |
            if [[ -f "${WORK}/data/fails.log" ]]; then
               while read line; do
                  eval "array=($line)"
                  status=${array[0]}
                  notest=${array[1]}
                  exit_code=${array[2]}

                  str="# Test $notest (exit code / desc.: $exit_code) #"
                  eval $(echo printf '"#%0.s"' {1..${#str}}) && printf "\n"
                  echo "$str"
                  eval $(echo printf '"#%0.s"' {1..${#str}}) && printf "\n"

                  if [[ "$(ls ${WORK}/reports/ | grep ${notest}- || true)" != "" ]]; then
                     report_file="$(ls ${WORK}/reports/${notest}-* | head -n 1)"
                     awk -v prefix="(log test $notest)" '{print prefix" "$0}' "$report_file"
                  else
                     echo "(warning) No report file found for test $notest (this might be normal depending on the test; check the description)"
                  fi
                  echo ""
               done < "${WORK}/data/fails.log"
            else
               >&2 echo "ERROR: could not find the file which contain the fails, and should exist"
               exit 1
            fi
